"""Description of the change

Revision ID: a86d9c8a034d
Revises: 
Create Date: 2024-01-10 23:03:33.840289

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import func  

# revision identifiers, used by Alembic.
revision: str = 'a86d9c8a034d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('created_at', sa.DateTime, default=func.now()))
    # ### end Alembic commands ###
